Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: true
  Max: 120
  Exclude:
    - 'db/seeds.rb'
    - 'config/initializers/*.rb'

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/Tab:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false
