Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: true
  Max: 120
  Exclude:
    - 'db/seeds.rb'
    - 'config/initializers/*.rb'

Style/StringLiterals:
  Enabled: false
